SELECT
	rc.CONSTRAINT_CATALOG AS RC_CONSTRAINT_CATALOG,
	rc.CONSTRAINT_SCHEMA AS RC_CONSTRAINT_SCHEMA,
	rc.CONSTRAINT_NAME AS RC_CONSTRAINT_NAME,
	rc.UNIQUE_CONSTRAINT_CATALOG AS RC_UNIQUE_CONSTRAINT_CATALOG,
	rc.UNIQUE_CONSTRAINT_SCHEMA AS RC_UNIQUE_CONSTRAINT_SCHEMA,
	rc.UNIQUE_CONSTRAINT_NAME AS RC_UNIQUE_CONSTRAINT_NAME,
	rc.MATCH_OPTION AS RC_MATCH_OPTION,
	rc.UPDATE_RULE AS RC_UPDATE_RULE,
	rc.DELETE_RULE AS RC_DELETE_RULE,
	rc.TABLE_NAME AS RC_TABLE_NAME,
	rc.REFERENCED_TABLE_NAME AS RC_REFERENCED_TABLE_NAME,
	kcu.CONSTRAINT_CATALOG AS KCU_CONSTRAINT_CATALOG,
	kcu.CONSTRAINT_SCHEMA AS KCU_CONSTRAINT_SCHEMA,
	kcu.CONSTRAINT_NAME AS KCU_CONSTRAINT_NAME,
	kcu.TABLE_CATALOG AS KCU_TABLE_CATALOG,
	kcu.TABLE_SCHEMA AS KCU_TABLE_SCHEMA,
	kcu.TABLE_NAME AS KCU_TABLE_NAME,
	kcu.COLUMN_NAME AS KCU_COLUMN_NAME,
	kcu.ORDINAL_POSITION AS KCU_ORDINAL_POSITION,
	kcu.POSITION_IN_UNIQUE_CONSTRAINT AS KCU_POSITION_IN_UNIQUE_CONSTRAINT,
	kcu.REFERENCED_TABLE_SCHEMA AS KCU_REFERENCED_TABLE_SCHEMA,
	kcu.REFERENCED_TABLE_NAME AS KCU_REFERENCED_TABLE_NAME,
	kcu.REFERENCED_COLUMN_NAME AS KCU_REFERENCED_COLUMN_NAME
FROM
  information_schema.REFERENTIAL_CONSTRAINTS rc
INNER JOIN information_schema.KEY_COLUMN_USAGE kcu
ON
   rc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
WHERE
	rc.CONSTRAINT_SCHEMA = :dbName AND rc.REFERENCED_TABLE_NAME = :tName AND kcu.REFERENCED_COLUMN_NAME = :relatedColumn;
