CREATE TABLE `df_internal_documents_registry` (
  `inr_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `inr_id_user` bigint unsigned NOT NULL COMMENT 'Користувач, який зареєстрував документ',
  `inr_id_carrier_type` bigint unsigned NOT NULL COMMENT 'Тип носія документа',
  `inr_id_document_location` bigint unsigned DEFAULT NULL COMMENT 'Фізичне місцезнаходження оригінала',
  `inr_number` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Номер документа',
  `inr_additional_number` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Додатковий номер',
  `inr_id_document_type` bigint unsigned NOT NULL COMMENT 'Тип документа',
  `inr_id_title` bigint unsigned NOT NULL COMMENT 'Назва чи заголовок документа',
  `inr_document_date` date DEFAULT NULL COMMENT 'Дата в документі',
  `inr_id_initiator` bigint unsigned NOT NULL COMMENT 'Ініціатор (користувач)',
  `inr_id_recipient` bigint unsigned DEFAULT NULL COMMENT 'Отримувач (користувач)',
  `inr_id_description` bigint unsigned DEFAULT NULL COMMENT 'Опис або короткий зміст документа',
  `inr_file_extension` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Розширення файлу завантаженого документа',
  `inr_id_status` bigint unsigned DEFAULT NULL COMMENT 'Статус документа (наприклад, "новий", "в обробці", "завершено")',
  `inr_id_responsible_user` bigint unsigned DEFAULT NULL COMMENT 'id відповідального за виконання',
  `inr_id_assigned_departament` bigint unsigned DEFAULT NULL COMMENT 'id відділа, якому призначено на виконання',
  `inr_id_assigned_user` bigint unsigned DEFAULT NULL COMMENT 'Призначений користувач обробки документа.',
  `inr_date_of_receipt_by_executor` datetime DEFAULT NULL COMMENT 'Дата надходження виконавцю',
  `inr_id_execution_control` bigint unsigned DEFAULT NULL COMMENT 'Контроль виконання: one-time, monthly, quarterly, annually',
  `inr_id_term_of_execution` bigint unsigned DEFAULT NULL COMMENT 'Термін виконання в днях',
  `inr_control_date` datetime DEFAULT NULL COMMENT 'Дата, до якої документ має бути виконаним',
  `inr_execution_date` datetime DEFAULT NULL COMMENT 'Дата виконання документа',
  `inr_distribution_scope` bigint unsigned DEFAULT NULL COMMENT 'Поширюється на',
  `inr_add_date` datetime NOT NULL,
  `inr_change_date` datetime NOT NULL,
  PRIMARY KEY (`inr_id`),
  UNIQUE KEY `uni_1` (`inr_number`),
  KEY `inr_user` (`inr_id_user`),
  KEY `inr_carrier_type` (`inr_id_carrier_type`),
  KEY `inr_document_location` (`inr_id_document_location`),
  KEY `inr_document_type` (`inr_id_document_type`),
  KEY `inr_title` (`inr_id_title`),
  KEY `inr_initiator` (`inr_id_initiator`),
  KEY `inr_recipient` (`inr_id_recipient`),
  KEY `inr_description` (`inr_id_description`),
  KEY `inr_status` (`inr_id_status`),
  KEY `inr_responsible_user` (`inr_id_responsible_user`),
  KEY `inr_assigned_departament` (`inr_id_assigned_departament`),
  KEY `inr_assigned_user` (`inr_id_assigned_user`),
  KEY `inr_execution_control` (`inr_id_execution_control`),
  KEY `inr_term_of_execution` (`inr_id_term_of_execution`),
  CONSTRAINT `inr_assigned_departament` FOREIGN KEY (`inr_id_assigned_departament`) REFERENCES `df_departments` (`dp_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_assigned_user` FOREIGN KEY (`inr_id_assigned_user`) REFERENCES `df_users` (`us_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_carrier_type` FOREIGN KEY (`inr_id_carrier_type`) REFERENCES `df_document_carrier_types` (`cts_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_description` FOREIGN KEY (`inr_id_description`) REFERENCES `df_document_descriptions` (`dds_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_document_location` FOREIGN KEY (`inr_id_document_location`) REFERENCES `df_departments` (`dp_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_document_type` FOREIGN KEY (`inr_id_document_type`) REFERENCES `df_document_types` (`dt_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_execution_control` FOREIGN KEY (`inr_id_execution_control`) REFERENCES `df_document_control_types` (`dct_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_initiator` FOREIGN KEY (`inr_id_initiator`) REFERENCES `df_users` (`us_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_recipient` FOREIGN KEY (`inr_id_recipient`) REFERENCES `df_users` (`us_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_responsible_user` FOREIGN KEY (`inr_id_responsible_user`) REFERENCES `df_users` (`us_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_status` FOREIGN KEY (`inr_id_status`) REFERENCES `df_user_statuses` (`uss_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_term_of_execution` FOREIGN KEY (`inr_id_term_of_execution`) REFERENCES `df_terms_of_execution` (`toe_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_title` FOREIGN KEY (`inr_id_title`) REFERENCES `df_document_titles` (`dts_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `inr_user` FOREIGN KEY (`inr_id_user`) REFERENCES `df_users` (`us_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Регістр вихідних документів із основними даними';

INSERT INTO `df_internal_documents_registry` VALUES ('1', '1', '4', '1', '00000001', '3672', '2', '3', '2024-05-03', '50', '50', '1', 'png', '2', '47', '1', '50', '2024-06-01 00:00:00', '3', '1', '2024-06-30 00:00:00', '', '', '2024-05-29 00:00:00', '2024-06-14 18:38:04');
INSERT INTO `df_internal_documents_registry` VALUES ('2', '1', '1', '', '00000002', '', '1', '1', '2024-05-29', '1', '1', '1', 'png', '1', '1', '', '59', '2024-06-08 00:00:00', '2', '', '2024-06-13 00:00:00', '2024-06-09 00:00:00', '', '2024-05-29 00:00:00', '2024-06-14 18:32:06');
