CREATE TABLE `df_outgoing_documents_registry` (
  `odr_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `odr_id_user` bigint unsigned NOT NULL COMMENT 'Користувач, який зареєстрував документ',
  `odr_id_document_type` bigint unsigned NOT NULL COMMENT 'Тип документа',
  `odr_id_carrier_type` bigint unsigned NOT NULL COMMENT 'Тип носія документа',
  `odr_id_document_location` bigint unsigned DEFAULT NULL COMMENT 'Фізичне місцезнаходження оригінала',
  `odr_number` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Номер вихідного документа',
  `odr_id_incoming_number` bigint unsigned DEFAULT NULL COMMENT 'Номер відповідного вхідного',
  `odr_registration_form_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Реєстраційний номер бланка',
  `odr_id_title` bigint unsigned NOT NULL COMMENT 'Назва чи заголовок документа',
  `odr_document_date` date DEFAULT NULL COMMENT 'Дата в документі',
  `odr_id_sender` bigint unsigned NOT NULL COMMENT 'Відправник (користувач)',
  `odr_id_recipient` bigint unsigned DEFAULT NULL COMMENT 'Отримувач (зовнішний)',
  `odr_id_description` bigint unsigned DEFAULT NULL COMMENT 'Опис або короткий зміст документа',
  `odr_file_extension` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Розширення файлу завантаженого документа',
  `odr_id_status` bigint unsigned DEFAULT NULL COMMENT 'Статус документа (наприклад, "новий", "в обробці", "завершено")',
  `odr_id_assigned_user` bigint unsigned DEFAULT NULL COMMENT 'Призначений користувач обробки документа.',
  `odr_id_execution_control` bigint unsigned DEFAULT NULL COMMENT 'Контроль виконання: one-time, monthly, quarterly, annually',
  `odr_control_date` datetime DEFAULT NULL COMMENT 'Дата, до якої документ має бути виконаним',
  `odr_execution_date` datetime DEFAULT NULL COMMENT 'Дата виконання документа',
  `odr_add_date` datetime NOT NULL,
  `odr_change_date` datetime NOT NULL,
  PRIMARY KEY (`odr_id`),
  UNIQUE KEY `uni_1` (`odr_number`),
  KEY `odr_user` (`odr_id_user`),
  KEY `odr_document_type` (`odr_id_document_type`),
  KEY `odr_carrier_type` (`odr_id_carrier_type`),
  KEY `odr_document_location` (`odr_id_document_location`),
  KEY `odr_incoming_number` (`odr_id_incoming_number`),
  KEY `odr_title` (`odr_id_title`),
  KEY `odr_sender` (`odr_id_sender`),
  KEY `odr_recipient` (`odr_id_recipient`),
  KEY `odr_description` (`odr_id_description`),
  KEY `odr_status` (`odr_id_status`),
  KEY `odr_assigned_user` (`odr_id_assigned_user`),
  KEY `odr_execution_control` (`odr_id_execution_control`),
  CONSTRAINT `odr_assigned_user` FOREIGN KEY (`odr_id_assigned_user`) REFERENCES `df_users` (`us_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `odr_carrier_type` FOREIGN KEY (`odr_id_carrier_type`) REFERENCES `df_document_carrier_types` (`cts_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `odr_description` FOREIGN KEY (`odr_id_description`) REFERENCES `df_document_descriptions` (`dds_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `odr_document_location` FOREIGN KEY (`odr_id_document_location`) REFERENCES `df_departments` (`dp_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `odr_document_type` FOREIGN KEY (`odr_id_document_type`) REFERENCES `df_document_types` (`dt_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `odr_execution_control` FOREIGN KEY (`odr_id_execution_control`) REFERENCES `df_document_control_types` (`dct_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `odr_incoming_number` FOREIGN KEY (`odr_id_incoming_number`) REFERENCES `df_incoming_documents_registry` (`idr_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `odr_recipient` FOREIGN KEY (`odr_id_recipient`) REFERENCES `df_document_senders` (`dss_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `odr_sender` FOREIGN KEY (`odr_id_sender`) REFERENCES `df_users` (`us_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `odr_status` FOREIGN KEY (`odr_id_status`) REFERENCES `df_document_statuses` (`dst_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `odr_title` FOREIGN KEY (`odr_id_title`) REFERENCES `df_document_titles` (`dts_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `odr_user` FOREIGN KEY (`odr_id_user`) REFERENCES `df_users` (`us_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Регістр вихідних документів із основними даними';

INSERT INTO `df_outgoing_documents_registry` VALUES ('1', '1', '1', '4', '4', '00000002', '4', '1234', '4', '2024-05-01', '1', '1', '12', 'png', '1', '', '2', '2024-06-09 00:00:00', '', '2024-05-26 00:00:00', '2024-05-31 17:37:37');
INSERT INTO `df_outgoing_documents_registry` VALUES ('2', '1', '8', '1', '', '00000012', '', '', '1', '2024-05-28', '50', '1', '1', 'png', '1', '', '', '', '', '2024-05-28 17:19:39', '2024-05-28 17:19:39');
INSERT INTO `df_outgoing_documents_registry` VALUES ('3', '1', '1', '4', '5', '00000013', '', '', '5', '2024-06-15', '1', '3', '11', 'docx', '1', '1', '2', '', '', '2024-06-15 15:47:04', '2024-06-15 15:47:04');
